# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlearn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='data_file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
