# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlearn', '0002_auto_20160827_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=250)),
                ('ftype', models.CharField(max_length=50)),
                ('fields', models.CharField(max_length=1000)),
                ('num_fields', models.CharField(max_length=500)),
                ('tex_fields', models.CharField(max_length=500)),
                ('predict_fields', models.CharField(max_length=500)),
                ('use_fields', models.CharField(max_length=1000)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlearn.Dataset')),
            ],
        ),
    ]
